# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: depcore.products::lang.product.label

# Model Form Field configuration
form: $/depcore/products/models/product/fields.yaml

# Model Class name
modelClass: Depcore\Products\Models\Product

# Default redirect location
defaultRedirect: depcore/products/products

# Create page
create:
    title: depcore.products::lang.product.create_title
    redirect: depcore/products/products/update/:id
    redirectClose: depcore/products/products

# Update page
update:
    title: depcore.products::lang.product.update_title
    redirect: depcore/products/products
    redirectClose: depcore/products/products

# Preview page
preview:
    title: depcore.products::lang.product.preview_title