# ===================================
#  Form Field Definitions
# ===================================

fields:
    name:
        label: depcore.products::lang.attributes.name.label
        type: text
    pivot[value]:
        label: depcore.products::lang.value.name.label
        type: relation
        dependsOn: attribute_id