# ===================================
#  List Column Definitions
# ===================================

columns:
    name:
        label: depcore.products::lang.attribute.label
        searchable: true
    pivot[value_id]:
        label: value