# ===================================
#  List Column Definitions
# ===================================

columns:
    name:
        label: depcore.products::lang.attribute.label
    pivot[value]:
        label: value
        type: partial
